const assert=require('node:assert/strict');
(async()=>{
 const {calculateKpi,kpiGrade,kpiDate,kpiSchedules,kpiCsv,KPI_WEIGHTS,kpiProofReady,mergeKpiBranch}=await import('../kpi-engine.js');
 let tests=0;const check=(label,fn)=>{fn();tests++;console.log('✓ '+label);};
 const staff=[{id:1,shId:'e1',name:'Alice',role:'budtender',approved:true},{id:2,shId:'e2',name:'Bob',role:'budtender',approved:true},{id:3,shId:'e3',name:'Charlie',role:'budtender',approved:true}];
 const month='2026-09';const start='2026-09-10T17:00:00+07:00',end='2026-09-11T02:00:00+07:00';
 const exact=[{expected:35,measured:'35'}];
 const shifts=staff.map(s=>({id:s.id,staffId:s.id,inAt:start,outAt:end,openTasksComplete:true,closeTasksComplete:true,openCheck:exact,closeCheck:exact,report:{cash:'0',sigOut:'A',proofPhoto:'photo'}}));
 const schedules=staff.map(s=>({staffId:s.id,date:'2026-09-10',start,end}));
 const targets=Object.fromEntries(staff.map(s=>[s.id,{sales:1000,upselling:1,crm:1,reviews:1,compliments:1}]));
 const evidence=staff.flatMap(s=>['crm','reviews','compliments'].map(type=>({month,staffId:s.id,type,reference:type+s.id,verified:true})));
 const storehub=staff.map(s=>({id:'tx'+s.id,employeeId:s.shId,total:1000,transactionTime:start}));
 const base={month,staff,schedules,shifts,targets,evidence,storehub,coverage:true,now:Date.parse('2026-10-01T00:00:00+07:00')};
 const calc=patch=>calculateKpi({...base,...patch});
 check('weights total 100',()=>assert.equal(Object.values(KPI_WEIGHTS).reduce((a,b)=>a+b),100));
 check('exact grade thresholds and full precision',()=>assert.deepEqual([69.999,70,79.999,80,89.999,90,100].map(kpiGrade),['D','C','C','B','B','A','A']));
 check('Bangkok month boundary and invalid dates',()=>{assert.equal(kpiDate('2026-08-31T17:00:00Z'),'2026-09-01');assert.equal(kpiDate('garbage'),'');});
 check('full attainment earns A / 3%',()=>{const r=calc().rows[0];assert.equal(r.score,100);assert.equal(r.grade,'A');assert.equal(r.commission,30);});
 check('exactly two bonuses, stable ID tie-break',()=>assert.deepEqual(calc().rows.map(r=>[r.staffId,r.bonus]),[[1,1500],[2,1500],[3,0]]));
 check('D warning without introducing a bonus qualification rule',()=>{const r=calc({evidence:[],shifts:[]}).rows[0];assert.equal(r.grade,'D');assert.equal(r.warning,true);assert.equal(r.commission,0);assert.equal(r.bonus,1500);});
 check('missing coverage holds grade and commission',()=>{const r=calc({coverage:false}).rows[0];assert.equal(r.grade,'Pending');assert.equal(r.commission,0);assert.equal(r.bonus,0);});
 check('missing targets cannot silently grade staff D',()=>assert.equal(calc({targets:{}}).rows[0].grade,'Pending'));
 check('missing roster blocks approval',()=>assert.equal(calc({schedules:[]}).ready,false));
 check('sync receipt dedup never adds local lifetime sales',()=>{const r=calc({local:[{id:'DCK-1789020000000',storehubId:'tx1',staffId:1,total:1000,createdAt:start}]}).rows[0];assert.equal(r.sales,1000);assert.equal(r.bills,1);});
 check('voids excluded, refunds netted and positive return total handled',()=>{const r=calc({storehub:[...storehub,{id:'return1',employeeId:'e1',total:600,originalTransactionId:'tx1',transactionType:'return',transactionTime:start},{id:'void1',employeeId:'e1',total:99999,isVoid:true,transactionTime:start}]}).rows.find(r=>r.staffId===1);assert.equal(r.sales,400);assert.equal(r.upselling,0);});
 check('negative sales cannot make negative commission or zero-sales awards',()=>{const r=calc({storehub:[{id:'refund',employeeId:'e1',total:-2000,transactionTime:start}]}).rows.find(r=>r.staffId===1);assert.equal(r.commission,0);assert.equal(r.bonus,0);});
 check('unmapped staff holds payroll approval',()=>assert.equal(calc({storehub:[...storehub,{id:'unknown',employeeId:'???',total:400,transactionTime:start}]}).ready,false));
 check('duplicate employee mapping holds approval',()=>assert.equal(calc({staff:[...staff,{id:9,shId:'e1',name:'Other',approved:true,role:'budtender'}]}).ready,false));
 check('owner sales intentionally excluded without blocking sellers',()=>{const r=calc({staff:[...staff,{id:9,shId:'owner',name:'CEO',role:'owner',approved:true}],storehub:[...storehub,{id:'ceotx',employeeId:'owner',total:9000,transactionTime:start}]});assert.equal(r.ready,true);assert.equal(r.rows.length,3);});
 check('unverified and duplicate evidence earn no extra points',()=>{const r=calc({evidence:[...evidence,...evidence,{month,staffId:1,type:'crm',reference:'fake',verified:false}]}).rows[0];assert.equal(r.crm,1);});
 check('overnight clock out belongs to shift start day',()=>assert.equal(calc().rows[0].onTime,1));
 check('15 minutes inclusive; 15m +1s late',()=>{const q=structuredClone(shifts);q[0].inAt='2026-09-10T17:15:00+07:00';assert.equal(calc({shifts:q}).rows.find(r=>r.staffId===1).onTime,1);q[0].inAt='2026-09-10T17:15:01+07:00';assert.equal(calc({shifts:q}).rows.find(r=>r.staffId===1).onTime,0);});
 check('arrival timestamp avoids punishing stock-count duration',()=>{const q=structuredClone(shifts);q[0].arrivedAt=start;q[0].inAt='2026-09-10T17:25:00+07:00';assert.equal(calc({shifts:q}).rows.find(r=>r.staffId===1).onTime,1);});
 check('early departure and no show fail attendance',()=>{const q=structuredClone(shifts);q[0].outAt='2026-09-11T01:59:59+07:00';assert.equal(calc({shifts:q}).rows.find(r=>r.staffId===1).onTime,0);assert.equal(calc({shifts:q.slice(1)}).rows.find(r=>r.staffId===1).onTime,0);});
 check('overcounts, unsigned or incomplete reports do not pass SOP',()=>{const q=structuredClone(shifts);q[0].closeCheck[0].measured='36';q[1].report.sigOut='';q[2].closeTasksComplete=false;assert.ok(calc({shifts:q}).rows.every(r=>r.completed===0));});
 check('future shifts do not reduce current provisional score',()=>assert.equal(calc({schedules:[...schedules,{staffId:1,date:'2026-09-30',start:'2026-09-30T17:00:00+07:00',end:'2026-10-01T02:00:00+07:00'}]}).rows[0].scheduled,1));
 check('changes invalidate approval snapshot',()=>assert.notEqual(calc().fingerprint,calc({evidence:[]}).fingerprint));
 check('unrelated month activity preserves approval snapshot',()=>assert.equal(calc().fingerprint,calc({local:[{id:'nextmonth',staffId:1,total:1000,createdAt:'2026-10-05T10:00:00Z'}],shifts:[...shifts,{id:444,staffId:1,inAt:'2026-10-05T10:00:00Z'}]}).fingerprint));
 check('roster resolves mapping and overnight times',()=>{const r=kpiSchedules({cells:{'bar|2026-09-10|N':{id:'roster1',name:'Alias'}}},[{id:'bar',slots:[{id:'N',label:'17:00–02:00'}]}],[{id:1,name:'Alice',rosterId:'roster1'}]);assert.equal(r.errors.length,0);assert.equal(r.schedules[0].end,'2026-09-10T19:00:00.000Z');});
 check('ambiguous roster names require manager resolution',()=>assert.equal(kpiSchedules({cells:{'bar|2026-09-10|N':{id:1,name:'Alice'}}},[],[{id:1,name:'Alice'},{id:2,name:'Alice'}]).errors.length,1));
 check('CSV contains grades / payout and neutralizes formulas',()=>{const r=calc();r.rows[0].name='=HYPERLINK("x")';const csv=kpiCsv(r);assert.ok(csv.includes("'="));assert.ok(csv.includes('Draft'));assert.ok(csv.includes('Top 2 Bonus THB'));});
 check('unlinked refunds remain pending until mapped',()=>{const tx=[...storehub,{id:'r1',employeeId:'e1',total:-400,transactionTime:start}];assert.equal(calc({storehub:tx}).ready,false);assert.equal(calc({storehub:tx,refundLinks:{r1:'tx1'}}).ready,true);});
 check('proof selection is mandatory for both CRM and reviews',()=>{assert.equal(kpiProofReady(),false);assert.equal(kpiProofReady({crm:{choice:'none',files:[]}}),false);assert.equal(kpiProofReady({crm:{choice:'none',files:[]},reviews:{choice:'none',files:[]}}),true);});
 check('proof selection cannot pass with empty, broken or unsafe images',()=>{assert.equal(kpiProofReady({crm:{choice:'proof',files:[]},reviews:{choice:'none'}}),false);assert.equal(kpiProofReady({crm:{choice:'proof',files:[{data:'data:text/html;base64,xxx'}]},reviews:{choice:'none'}}),false);assert.equal(kpiProofReady({crm:{choice:'proof',files:[{data:'data:image/jpeg;base64,xxx'}]},reviews:{choice:'none'}}),true);});
 check('reuploaded identical image gets only one evidence credit',()=>{const image='data:image/jpeg;base64,abc';const ev=[{month,staffId:1,type:'crm',reference:'a',attachment:image,verified:true},{month,staffId:1,type:'crm',reference:'b',attachment:image,verified:true}];assert.equal(calc({evidence:ev}).rows.find(r=>r.staffId===1).crm,1);});
 check('branch packages map staff by identity and reset remote verification',()=>{const payload={version:1,month,device:'tablet2',staff:[{id:99,name:'Alice',shId:'e1'}],shifts:[{...shifts[0],staffId:99}],evidence:[{id:1,month,staffId:99,type:'crm',reference:'customer',verified:true}]};const merged=mergeKpiBranch(payload,{month,staff,shifts:[],evidence:[]});assert.equal(merged.shifts[0].staffId,1);assert.equal(merged.evidence[0].verified,false);const again=mergeKpiBranch(payload,{month,staff,shifts:merged.shifts,evidence:merged.evidence});assert.equal(again.evidence.length,1);assert.equal(again.shifts.length,1);});
 check('wrong-month and unmapped branch files are refused',()=>{assert.throws(()=>mergeKpiBranch({version:1,month:'2026-08',device:'x',staff:[],shifts:[],evidence:[]},{month,staff,shifts:[],evidence:[]}));assert.throws(()=>mergeKpiBranch({version:1,month,device:'x',staff:[{id:99,name:'Unknown'}],shifts:[],evidence:[]},{month,staff,shifts:[],evidence:[]}));});
 console.log(`\n${tests} monthly KPI tests passed`);
})().catch(e=>{console.error(e);process.exit(1)});
