import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {chromium} from './_playwright.mjs';
const month='2026-09',time='2026-09-10T09:00:00+07:00',end='2026-09-10T18:00:00+07:00';
const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9AAAAABJRU5ErkJggg==','base64');
const staff=[{id:1,name:'Bryan (CEO)',pin:'110114',role:'owner',approved:true,branch:'Pattanakarn',payType:'monthly',wage:60000,clockIns:[]},...['Alice','Bob'].map((name,i)=>({id:i+2,shId:'e'+(i+2),name,pin:'',role:'budtender',approved:true,branch:i?'Sathorn':'Pattanakarn',payType:'monthly',wage:19000,clockIns:[]}))];
const schedules={days:[{date:'2026-09-10'}],cells:{'ptk|2026-09-10|D':{id:2,name:'Alice'},'st|2026-09-10|D':{id:3,name:'Bob'}}};
const shifts=staff.slice(1).map(s=>({id:'old'+s.id,staffId:s.id,staffName:s.name,inAt:time,outAt:end,branch:s.branch,openTasksComplete:true,closeTasksComplete:true,openCheck:[],closeCheck:[],report:{cash:'0',sigOut:s.name,proofPhoto:'data:image/png;base64,'+image.toString('base64')}}));
const sales=staff.slice(1).map(s=>({id:'tx'+s.id,employeeId:s.shId,total:1000,transactionTime:time}));
const evidence=staff.slice(1).flatMap(s=>['crm','reviews','compliments'].map(type=>({id:type+s.id,month,staffId:s.id,type,reference:type+s.id,verified:true})));
const targets=Object.fromEntries(staff.slice(1).map(s=>[s.id,{sales:1000,upselling:1,crm:1,reviews:1,compliments:1}]));
const source=fs.readFileSync(new URL('../app.fixed.jsx',import.meta.url),'utf8');
const core=vm.runInNewContext(source.slice(source.indexOf('const CORE_STAFF='),source.indexOf('const INIT_EXPENSES='))+'CORE_STAFF;');
const seedStaff=staff.concat(core.map(s=>({...s,approved:false})));
const data={months:{[month]:{targets,sales,loadedAt:time,coverage:true,missingPass:false}},evidence,approvals:{}};
const errs=[];let checks=0;
const b=await chromium.launch();const p=await b.newPage({viewport:{width:1280,height:1000},acceptDownloads:true});p.on('pageerror',e=>errs.push(e.message));
try {
await p.route('**/stub.js',route=>route.fulfill({contentType:'application/javascript',body:'window.__SH_STUB={products:[],transactions:[],customers:[]};'}));
await p.addInitScript(seed=>{if(localStorage.getItem('kpi_test_seed'))return;localStorage.setItem('kpi_test_seed','1');for(const [k,v] of Object.entries(seed))localStorage.setItem(k,JSON.stringify(v));}, {dank_staff:seedStaff,dank_shift_staff:[],dank_shift_staff_seed_version:4,dank_shift_roster:{[month]:schedules},dank_shift_locs:[{id:'ptk',name:'Pattanakarn',slots:[{id:'D',label:'09:00–18:00'}]},{id:'st',name:'Sathorn',slots:[{id:'D',label:'09:00–18:00'}]}],dank_shifts:shifts,dank_monthly_kpi_v1:data});
let failSync=false;
await p.route('**/api/storehub/**',async route=>{let result=[];const url=route.request().url();if(url.includes('/transactions'))result=sales;if(failSync&&url.includes('/transactions'))return route.fulfill({status:502,json:{error:'test unavailable'}});await route.fulfill({json:result});});
p.setDefaultTimeout(7000);
await p.goto('http://127.0.0.1:8799/pos/testrun/test2.html');await p.waitForTimeout(500);
for(const d of '110114')await p.getByRole('button',{name:d,exact:true}).first().click();await p.waitForTimeout(600);
await p.getByRole('button',{name:'ไว้ก่อน',exact:true}).click().catch(()=>{});
const check=(label,condition)=>{assert.ok(condition,label);checks++;console.log('✓ '+label);};
const openKpi=async()=>{await p.getByRole('button',{name:/👤\s*พนักงาน/}).click();await p.getByRole('button',{name:'📊 KPI',exact:true}).click();};
await openKpi();await p.getByLabel('KPI month').fill(month);await p.getByLabel('KPI staff',{exact:true}).selectOption('2');
check('cross-shop leaderboard displays both grades and bonuses',(await p.getByRole('dialog').innerText()).includes('A · 100.00/100')&&(await p.getByRole('dialog').innerText()).includes('฿1,530'));
await p.getByLabel('KPI approval note').fill('Monthly payroll reviewed against every branch');await p.getByRole('button',{name:/Approve commission/}).click();
check('manager approval persists snapshot',await p.evaluate(()=>!!JSON.parse(localStorage.getItem('dank_monthly_kpi_v1')).approvals['2026-09']));
const dl=p.waitForEvent('download');await p.getByRole('button',{name:/Export$/}).click();const download=await dl;check('approved monthly report downloads',download.suggestedFilename().includes('approved.csv'));
await p.getByLabel('Target sales').fill('2000');await p.getByRole('button',{name:/Save targets/}).click();
check('changed targets invalidate payout approval',(await p.getByRole('dialog').innerText()).includes('Changed since approval'));
await p.getByLabel('Evidence type').selectOption('compliments');await p.getByLabel('Evidence reference').fill('customer-receipt-44');await p.getByLabel('Evidence comment').fill('Alice explained everything clearly');await p.getByRole('button',{name:/Submit evidence/}).click();
let row=p.getByRole('dialog').locator('div').filter({hasText:/^compliments · customer-receipt-44/}).last();await row.getByRole('button',{name:/Verify$/}).click();
check('new customer compliment is verified',await p.evaluate(()=>JSON.parse(localStorage.getItem('dank_monthly_kpi_v1')).evidence.find(e=>e.reference==='customer-receipt-44').verified));
await row.getByRole('button',{name:/Unverify$/}).click();
await p.getByLabel('Roster staff mapping').selectOption('');await p.getByLabel('StoreHub employee ID').fill('e2');await p.getByLabel('Target sales').click();
const branchDownload=p.waitForEvent('download');await p.getByRole('button',{name:/Export branch$/}).click();const branchFile=await branchDownload;check('branch records export without staff PINs',!fs.readFileSync(await branchFile.path(),'utf8').includes('110114'));
const incoming={version:1,month,device:'second-tablet',staff:[{id:99,name:'Alice',shId:'e2'}],shifts:[{...shifts[0],staffId:99}],evidence:[{id:'remote1',month,staffId:99,type:'crm',reference:'remote-customer',verified:true}]};
await p.getByLabel('Import KPI branch file').setInputFiles({name:'branch.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(incoming))});await p.getByText(/Imported; new evidence requires verification/).waitFor();check('branch import maps staff and requires fresh verification',await p.evaluate(()=>{const e=JSON.parse(localStorage.getItem('dank_monthly_kpi_v1')).evidence.find(x=>x.reference==='remote-customer');return e.staffId===2&&!e.verified;}));
await p.getByLabel('Import KPI branch file').setInputFiles({name:'wrong.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...incoming,month:'2026-08'}))});await p.getByText(/Import failed/).waitFor();check('wrong month branch file is rejected',await p.evaluate(()=>JSON.parse(localStorage.getItem('dank_monthly_kpi_v1')).evidence.filter(x=>x.reference==='remote-customer').length===1));
await p.getByLabel('Confirm KPI data coverage').check();await p.getByLabel('KPI month').fill('2026-10');await p.getByLabel('KPI approval note').fill('Cannot pay an incomplete month');check('current month approval is disabled',await p.getByRole('button',{name:/Approve commission/}).isDisabled());
failSync=true;await p.getByRole('button',{name:/Refresh sales/}).click();await p.getByRole('alert').filter({hasText:'StoreHub HTTP 502'}).waitFor();check('failed sync shows error and remains retryable',await p.getByRole('button',{name:/Refresh sales/}).isEnabled());failSync=false;await p.getByRole('button',{name:/Refresh sales/}).click();await p.waitForTimeout(150);check('retry clears error',await p.getByRole('alert').filter({hasText:'StoreHub HTTP 502'}).count()===0);
await p.setViewportSize({width:390,height:844});await p.getByLabel('KPI month').fill(month);
await p.waitForTimeout(250);
check('mobile KPI has no horizontal overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
fs.mkdirSync(new URL('./out/',import.meta.url),{recursive:true});await p.screenshot({path:new URL('./out/monthly-kpi-mobile.png',import.meta.url).pathname});
await p.getByLabel('Close KPI').click();await p.setViewportSize({width:1280,height:1000});
// Seed a currently open shift to exercise the real close checklist and report.
await p.evaluate(()=>{const list=JSON.parse(localStorage.getItem('dank_shifts'));list.unshift({id:'openproof',staffId:2,staffName:'Alice',branch:'Pattanakarn',inAt:new Date().toISOString(),slot:'Day',outAt:null,openTasksComplete:true,openCheck:[],sales0:0});localStorage.setItem('dank_shifts',JSON.stringify(list));});
await p.reload();await p.waitForTimeout(400);for(const d of '110114')await p.getByRole('button',{name:d,exact:true}).first().click();await p.waitForTimeout(500);
await p.getByRole('button',{name:'ไว้ก่อน',exact:true}).click().catch(()=>{});
await p.getByRole('button',{name:/🕐\s*กะ Shift/}).click();await p.getByRole('button',{name:'⏹ ปิดกะ Out',exact:true}).first().click();await p.getByRole('button',{name:/ติ๊กทั้งหมด/}).click();await p.getByRole('button',{name:/ต่อไป → นับสต็อก/}).click();
// Empty inventory skips the stock form directly into the close report.
await p.getByLabel('crm no proof').waitFor();await p.locator('input[placeholder="เช่น BR"]').fill('AL');
await p.locator('input[type=file][capture=environment]').last().setInputFiles({name:'stock.png',mimeType:'image/png',buffer:image});await p.waitForTimeout(250);
check('close blocked without CRM/review choice',await p.getByRole('button',{name:/ส่งรายงาน \+ ปิดกะ/}).isDisabled());
await p.getByLabel('crm no proof').click();check('one choice is insufficient',await p.getByRole('button',{name:/ส่งรายงาน \+ ปิดกะ/}).isDisabled());
await p.getByLabel('reviews proof upload').setInputFiles({name:'review.png',mimeType:'image/png',buffer:image});await p.getByText(/แนบ 1 รูป/).waitFor();check('none plus uploaded proof allows close',await p.getByRole('button',{name:/ส่งรายงาน \+ ปิดกะ/}).isEnabled());
await p.getByLabel('reviews remove proof 1').click();check('removing final proof makes choice required again',await p.getByRole('button',{name:/ส่งรายงาน \+ ปิดกะ/}).isDisabled());
await p.getByLabel('reviews no proof').click();check('two explicit None choices allow close',await p.getByRole('button',{name:/ส่งรายงาน \+ ปิดกะ/}).isEnabled());
await p.getByLabel('crm proof upload').setInputFiles({name:'crm.png',mimeType:'image/png',buffer:image});await p.getByText(/แนบ 1 รูป/).waitFor();await p.getByRole('button',{name:/ส่งรายงาน \+ ปิดกะ/}).click();await p.waitForTimeout(250);
check('proof is preserved as unverified KPI evidence',await p.evaluate(()=>{const d=JSON.parse(localStorage.getItem('dank_monthly_kpi_v1'));return d.evidence.some(e=>e.shiftId==='openproof'&&e.type==='crm'&&e.attachment&&!e.verified);}));
check('none is preserved in closed shift report',await p.evaluate(()=>JSON.parse(localStorage.getItem('dank_shifts')).find(s=>s.id==='openproof').report.kpiProofs.reviews.choice==='none'));
await p.reload();await p.waitForTimeout(300);check('proof survives refresh',await p.evaluate(()=>JSON.parse(localStorage.getItem('dank_monthly_kpi_v1')).evidence.some(e=>e.shiftId==='openproof'&&e.attachment)));
for(const d of '110114')await p.getByRole('button',{name:d,exact:true}).first().click();await p.waitForTimeout(300);await openKpi();await p.getByLabel('KPI staff',{exact:true}).selectOption('2');await p.getByText('ดูรูปหลักฐาน / View uploaded proof',{exact:true}).click();check('manager can view uploaded shift proof inside the app',await p.getByAltText('crm uploaded proof').isVisible());
// Isolated September retrospective with unavailable KPI records.
const q=await b.newPage({viewport:{width:1280,height:1000},acceptDownloads:true});q.on('pageerror',e=>errs.push(e.message));
await q.route('**/stub.js',route=>route.fulfill({contentType:'application/javascript',body:'window.__SH_STUB={products:[],transactions:[],customers:[]};'}));
await q.route('**/api/storehub/**',route=>route.fulfill({json:[]}));
await q.addInitScript(seed=>{if(localStorage.getItem('provisional_seed'))return;localStorage.setItem('provisional_seed','1');for(const [k,v] of Object.entries(seed))localStorage.setItem(k,JSON.stringify(v));},{dank_staff:seedStaff,dank_shift_staff:[],dank_shift_staff_seed_version:4,dank_shift_roster:{},dank_shifts:[],dank_monthly_kpi_v1:{months:{[month]:{sales:[],loadedAt:time,coverage:false}},evidence:[],approvals:{}}});
const loginQ=async()=>{for(const d of '110114')await q.getByRole('button',{name:d,exact:true}).first().click();await q.getByRole('button',{name:'ไว้ก่อน',exact:true}).click().catch(()=>{});await q.getByRole('button',{name:/👤\s*พนักงาน/}).click();await q.getByRole('button',{name:'📊 KPI',exact:true}).click();await q.getByLabel('KPI month').fill(month);};
await q.goto('http://127.0.0.1:8799/pos/testrun/test2.html');await loginQ();
check('September defaults to clearly labelled provisional A',(await q.getByRole('dialog').innerText()).includes('A · 100.00/100 · ชั่วคราว / Provisional'));
check('unavailable data does not enable payroll approval',await q.getByRole('button',{name:/Approve commission/}).isDisabled());
const provisionalDownload=q.waitForEvent('download');await q.getByRole('button',{name:/Export$/}).click();const provisionalCsv=fs.readFileSync(await (await provisionalDownload).path(),'utf8');check('CSV discloses provisional assumptions',provisionalCsv.includes('Provisional')&&provisionalCsv.includes('Missing sales target'));
await q.getByLabel('September missing KPI pass').uncheck();check('manager can disable exception and restore Pending',(await q.getByRole('dialog').innerText()).includes('Pending · 0.00/100'));
await q.reload();await loginQ();check('disabled month policy survives reload',!await q.getByLabel('September missing KPI pass').isChecked());await q.getByLabel('September missing KPI pass').check();
await q.setViewportSize({width:390,height:844});await q.waitForTimeout(250);check('provisional mobile dashboard has no overflow',await q.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await q.screenshot({path:new URL('./out/september-provisional-mobile.png',import.meta.url).pathname});
await q.getByLabel('KPI month').fill('2026-10');check('exception is not offered for October',await q.getByLabel('September missing KPI pass').count()===0);await q.close();
assert.deepEqual(errs,[]);console.log(`${checks} browser checks passed; zero page errors`);
} catch(e) {console.log('Wide elements:',await p.evaluate(()=>[...document.querySelectorAll('body *')].map(e=>({tag:e.tagName,text:(e.innerText||'').slice(0,70),right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width})).filter(x=>x.right>window.innerWidth+1&&x.width>0).slice(-12)));console.log('UI excerpt:',(await p.locator('body').innerText()).slice(0,2200));throw e;} finally {await b.close();}
